### PR TITLE
Change to use pre-built docker image

### PR DESCRIPTION
**Pull request by Greg-Hawkridge**
Also resolves Issue #5

### CODE REVIEW

**Comment by Greg-Hawkridge** [comment]
@chen2181 - can you check that this works correctly (download the branch directly on a Pi and a Rock) and then approve - It should work, but the changes I've made have been from memory of what I did for job tracking before I went on leave

**Comment by chen2181** [comment]
@Greg-Hawkridge  Modify in file topic_mapper.py,   line 14,  mapper_conf = config['topic_rewriter'], then it works.

**Review by LukasChenChen — CHANGES_REQUESTED** [review]
Modify in file topic_mapper.py, line 14, to,  mapper_conf = config['topic_rewriter'], then it works.

**Comment by Greg-Hawkridge** [comment]
> Modify in file topic_mapper.py, line 14, to, mapper_conf = config['topic_rewriter'], then it works.

It should be [already](https://github.com/DigitalShoestringSolutions/AWSRelay/blob/49ef3d545b04b091d6d7275faef666eecee6bd04/aws_relay/code/topic_rewriter.py#L14)

**Review by LukasChenChen — APPROVED** [review]

**Review by chen2181 — APPROVED** [review]
working ok

**Review by chen2181 — APPROVED** [review]

**Pull request merged**
